# Generated by Django 5.0.6 on 2026-01-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0042_remove_room_bingosync_r_created_833796_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='board_height',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='board_width',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
