# Generated by Django 5.0.6 on 2026-01-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0043_game_board_height_game_board_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='square',
            name='board_height',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='square',
            name='board_width',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
